import { useEffect, useState } from "react";
import { ArrowLeft, Check, Copy, FileImage, FloppyDisk, Scan } from "@phosphor-icons/react";
import { OutputActions } from "../../components/OutputActions";
import { saveTextOutput } from "../../services/text-output";
import { extractText, getOcrRuntime, pickOcrFile, type OcrLanguage, type OcrRuntime } from "./local-ocr.service";
interface Props { onBack: () => void; }
function name(path: string) { return path.split(/[\\/]/).pop() ?? path; }
export function LocalOcr({ onBack }: Props) {
  const [path, setPath] = useState(""); const [language, setLanguage] = useState<OcrLanguage>("spa+eng"); const [text, setText] = useState(""); const [runtime, setRuntime] = useState<OcrRuntime | null>(null); const [processing, setProcessing] = useState(false); const [copied, setCopied] = useState(false); const [savedPath, setSavedPath] = useState(""); const [error, setError] = useState("");
  useEffect(() => { void getOcrRuntime().then(setRuntime).catch((cause) => setError(String(cause))); }, []);
  async function choose() { try { const selected = await pickOcrFile(); if (selected) { setPath(selected); setText(""); } setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } }
  async function run() { setProcessing(true); try { setText(await extractText(path, language)); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setProcessing(false); } }
  async function copy() { await navigator.clipboard.writeText(text); setCopied(true); window.setTimeout(() => setCopied(false), 1200); }
  async function saveText() { try { const saved = await saveTextOutput(text, "ocr.txt", "Texto", ["txt"]); if (saved) setSavedPath(saved); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } }
  const isPdf = path.toLowerCase().endsWith(".pdf");
  return <section className="tool-view"><button className="back-button" onClick={onBack}><ArrowLeft /> Volver a herramientas</button><div className="tool-heading"><span className="tool-heading-icon ocr-icon"><Scan weight="duotone" /></span><div><p className="eyebrow">Productividad</p><h1>OCR local</h1><p>Extrae texto de capturas, fotografías y documentos PDF escaneados.</p></div></div>
    <div className="runtime-status"><span className={runtime?.tesseract ? "runtime-dot ready" : "runtime-dot"} /> Tesseract {runtime?.tesseract ? "disponible" : "no encontrado"}<span className={runtime?.pdftoppm ? "runtime-dot ready" : "runtime-dot"} /> PDF {runtime?.pdftoppm ? "disponible" : "no disponible"}</div>
    <div className="file-tool-panel"><button className="media-picker" onClick={() => void choose()}><FileImage weight="duotone" /><span><strong>{path ? name(path) : "Seleccionar imagen o PDF"}</strong><small>PNG, JPG, WebP, BMP, TIFF o PDF · máximo 50 MB</small></span></button><div className="ocr-controls"><label>Idioma<select value={language} onChange={(event) => setLanguage(event.target.value as OcrLanguage)}><option value="spa+eng">Español + inglés</option><option value="spa">Español</option><option value="eng">Inglés</option></select></label><button className="primary-button compact" disabled={!path || processing || !runtime?.tesseract || (isPdf && !runtime?.pdftoppm)} onClick={() => void run()}>{processing ? "Reconociendo…" : "Extraer texto"}</button></div>
      {!runtime?.tesseract && <p className="tool-notice">Falta Tesseract OCR. Instálalo durante el desarrollo con: <code>winget install UB-Mannheim.TesseractOCR</code></p>}{text && <div className="ocr-result"><div><strong>Texto reconocido</strong><span><button onClick={() => void copy()}>{copied ? <Check /> : <Copy />}{copied ? "Copiado" : "Copiar"}</button><button onClick={() => void saveText()}><FloppyDisk /> Guardar TXT</button></span></div><textarea value={text} onChange={(event) => setText(event.target.value)} spellCheck={false} /></div>}{savedPath && <OutputActions path={savedPath} />}{error && <p className="error-text tool-error">{error}</p>}</div></section>;
}
