import {
  AiScan,
  Archive,
  AudioWaveform,
  Blocks,
  BracesContent,
  Calculator,
  CircuitBoard,
  Download,
  FileText,
  Image,
  Images,
  Lock,
  MagicEdit,
  Proportions,
  Repeat,
  ScanBarcode,
  Sparkles,
  Video,
} from "pixelarticons/react";
import type { ToolDefinition } from "../types/tool";

export const tools: ToolDefinition[] = [
  {
    id: "password-generator",
    name: "Contraseñas seguras",
    description: "Genera contraseñas y frases aleatorias sin guardar nada.",
    category: "Productividad",
    icon: Lock,
    accent: "#00e68a",
    status: "available",
  },
  {
    id: "qr-generator",
    name: "Generador QR",
    description: "Convierte enlaces o texto en un código QR listo para guardar.",
    category: "Productividad",
    icon: ScanBarcode,
    accent: "#00e68a",
    status: "available",
  },
  {
    id: "background-remover",
    name: "Quitar fondo blanco",
    description: "Convierte fondos blancos en transparencia y exporta PNG.",
    category: "Imágenes",
    icon: MagicEdit,
    accent: "#00e68a",
    status: "available",
  },
  {
    id: "ai-background-remover",
    name: "Quitar fondo IA",
    description: "Recorta sujetos y elimina fondos complejos con IA local.",
    category: "Imágenes",
    icon: Sparkles,
    accent: "#00e68a",
    status: "available",
  },
  {
    id: "image-converter",
    name: "Convertir imágenes",
    description: "Convierte PNG, JPG y WebP de forma local y por lotes.",
    category: "Imágenes",
    icon: Image,
    accent: "#00e68a",
    status: "available",
  },
  {
    id: "image-compressor",
    name: "Comprimir imágenes",
    description: "Reduce imágenes por lotes y compara el peso antes y después.",
    category: "Imágenes",
    icon: Images,
    accent: "#00e68a",
    status: "available",
  },
  {
    id: "image-resizer",
    name: "Redimensionar",
    description: "Cambia medidas y peso conservando la mejor calidad posible.",
    category: "Imágenes",
    icon: Proportions,
    accent: "#00e68a",
    status: "available",
  },
  {
    id: "pdf-tools",
    name: "Herramientas PDF",
    description: "Une, extrae páginas y convierte documentos PDF.",
    category: "PDF",
    icon: FileText,
    accent: "#00e68a",
    status: "available",
  },
  {
    id: "advanced-pdf-optimizer",
    name: "Optimizar PDF avanzado",
    description: "Reduce PDFs usando Ghostscript o MuPDF local.",
    category: "PDF",
    icon: Archive,
    accent: "#00e68a",
    status: "available",
  },
  {
    id: "video-converter",
    name: "Convertir multimedia",
    description: "Convierte audio y video a seis formatos usando FFmpeg.",
    category: "Multimedia",
    icon: Video,
    accent: "#00e68a",
    status: "available",
  },
  {
    id: "media-downloader",
    name: "Descarga permitida",
    description: "Descarga o convierte medios cuando tengas permiso para hacerlo.",
    category: "Multimedia",
    icon: Download,
    accent: "#00e68a",
    status: "available",
  },
  {
    id: "local-transcription",
    name: "Transcripción local",
    description: "Extrae texto de audio o video usando Whisper local.",
    category: "Multimedia",
    icon: AudioWaveform,
    accent: "#00e68a",
    status: "available",
  },
  {
    id: "local-ocr",
    name: "OCR local",
    description: "Extrae texto de capturas, fotografías y PDF escaneados.",
    category: "Productividad",
    icon: AiScan,
    accent: "#00e68a",
    status: "available",
  },
  {
    id: "document-converter",
    name: "Markdown, HTML y texto",
    description: "Convierte contenido estructurado sin subirlo a internet.",
    category: "Productividad",
    icon: BracesContent,
    accent: "#00e68a",
    status: "available",
  },
  {
    id: "text-diff",
    name: "Comparar texto",
    description: "Compara textos y archivos con una vista clara de diferencias.",
    category: "Productividad",
    icon: FileText,
    accent: "#00e68a",
    status: "available",
  },
  {
    id: "unit-converter",
    name: "Conversor universal",
    description: "Convierte unidades, fechas y zonas horarias sin conexión.",
    category: "Productividad",
    icon: Calculator,
    accent: "#00e68a",
    status: "available",
  },
  {
    id: "batch-renamer",
    name: "Renombrar archivos",
    description: "Renombra grupos de archivos con reglas reutilizables.",
    category: "Productividad",
    icon: Repeat,
    accent: "#00e68a",
    status: "available",
  },
  {
    id: "plugin-manager",
    name: "Plugins seguros",
    description: "Audita plugins locales, firmas y permisos explícitos.",
    category: "Productividad",
    icon: Blocks,
    accent: "#00e68a",
    status: "available",
  },
  {
    id: "dependency-center",
    name: "Centro de dependencias",
    description: "Verifica FFmpeg, OCR, IA local, PDF y motores externos.",
    category: "Productividad",
    icon: CircuitBoard,
    accent: "#00e68a",
    status: "available",
  },
];

export const categories = ["Todas", "Imágenes", "PDF", "Productividad", "Multimedia"] as const;
