import {
  ArrowsClockwise,
  FilePdf,
  ImageSquare,
  Gauge,
  MagicWand,
  Sparkle,
  QrCode,
  Resize,
  VideoCamera,
  DownloadSimple,
  Waveform,
  FileText,
  FileCode,
  Scan,
  Ruler,
  FileArchive,
  Plug,
  PlugsConnected,
} from "@phosphor-icons/react";
import type { ToolDefinition } from "../types/tool";

export const tools: ToolDefinition[] = [
  {
    id: "qr-generator",
    name: "Generador QR",
    description: "Convierte enlaces o texto en un código QR listo para guardar.",
    category: "Productividad",
    icon: QrCode,
    accent: "#a78bfa",
    status: "available",
  },
  {
    id: "background-remover",
    name: "Quitar fondo blanco",
    description: "Convierte fondos blancos en transparencia y exporta PNG.",
    category: "Imágenes",
    icon: MagicWand,
    accent: "#fb7185",
    status: "available",
  },
  {
    id: "ai-background-remover",
    name: "Quitar fondo IA",
    description: "Recorta sujetos y elimina fondos complejos con IA local.",
    category: "ImÃ¡genes",
    icon: Sparkle,
    accent: "#f472b6",
    status: "available",
  },
  {
    id: "image-converter",
    name: "Convertir imágenes",
    description: "Convierte PNG, JPG y WebP de forma local y por lotes.",
    category: "Imágenes",
    icon: ImageSquare,
    accent: "#38bdf8",
    status: "available",
  },
  {
    id: "image-compressor",
    name: "Comprimir imágenes",
    description: "Reduce imágenes por lotes y compara el peso antes y después.",
    category: "Imágenes",
    icon: Gauge,
    accent: "#2dd4bf",
    status: "available",
  },
  {
    id: "image-resizer",
    name: "Redimensionar",
    description: "Cambia medidas y peso conservando la mejor calidad posible.",
    category: "Imágenes",
    icon: Resize,
    accent: "#34d399",
    status: "available",
  },
  {
    id: "pdf-tools",
    name: "Herramientas PDF",
    description: "Une, extrae páginas y optimiza documentos PDF.",
    category: "PDF",
    icon: FilePdf,
    accent: "#f87171",
    status: "available",
  },
  {
    id: "video-converter",
    name: "Convertir multimedia",
    description: "Convierte audio y video a seis formatos usando FFmpeg.",
    category: "Multimedia",
    icon: VideoCamera,
    accent: "#fbbf24",
    status: "available",
  },
  {
    id: "media-downloader",
    name: "Descarga permitida",
    description: "Descarga o convierte medios cuando tengas permiso para hacerlo.",
    category: "Multimedia",
    icon: DownloadSimple,
    accent: "#fb923c",
    status: "available",
  },
  {
    id: "local-transcription",
    name: "Transcripción local",
    description: "Extrae texto de audio o video usando Whisper local.",
    category: "Multimedia",
    icon: Waveform,
    accent: "#fbbf24",
    status: "available",
  },
  {
    id: "advanced-pdf-optimizer",
    name: "Optimizar PDF avanzado",
    description: "Reduce PDFs con perfiles de Ghostscript y compara el ahorro.",
    category: "PDF",
    icon: FileArchive,
    accent: "#fb7185",
    status: "available",
  },
  {
    id: "local-ocr",
    name: "OCR local",
    description: "Extrae texto de capturas, fotografías y PDF escaneados.",
    category: "Productividad",
    icon: Scan,
    accent: "#60a5fa",
    status: "available",
  },
  {
    id: "document-converter",
    name: "Markdown, HTML y texto",
    description: "Convierte contenido estructurado sin subirlo a internet.",
    category: "Productividad",
    icon: FileCode,
    accent: "#f472b6",
    status: "available",
  },
  {
    id: "text-diff",
    name: "Comparar texto",
    description: "Compara textos y archivos con una vista clara de diferencias.",
    category: "Productividad",
    icon: FileText,
    accent: "#c084fc",
    status: "available",
  },
  {
    id: "unit-converter",
    name: "Conversor universal",
    description: "Convierte unidades, fechas y zonas horarias sin conexión.",
    category: "Productividad",
    icon: Ruler,
    accent: "#60a5fa",
    status: "available",
  },
  {
    id: "batch-renamer",
    name: "Renombrar archivos",
    description: "Renombra grupos de archivos con reglas reutilizables.",
    category: "Productividad",
    icon: ArrowsClockwise,
    accent: "#22d3ee",
    status: "available",
  },
  {
    id: "plugin-manager",
    name: "Plugins seguros",
    description: "Audita plugins locales, firmas y permisos explícitos.",
    category: "Productividad",
    icon: Plug,
    accent: "#a78bfa",
    status: "available",
  },
  {
    id: "dependency-center",
    name: "Centro de dependencias",
    description: "Verifica FFmpeg, OCR, IA local, PDF y motores externos.",
    category: "Productividad",
    icon: PlugsConnected,
    accent: "#34d399",
    status: "available",
  },
];

export const categories = ["Todas", "Imágenes", "PDF", "Productividad", "Multimedia"] as const;
